### ISSUE TITLE
"illegal value" when setting UsageCode

### ISSUE THREAD

**Issue by cbenhagen** [markreidvfx/pyaaf#36]
```python
import aaf

f = aaf.open()
comp_mob = f.create.CompositionMob()
comp_mob["UsageCode"].value = "Usage_TopLevel"
```
```python
Traceback (most recent call last):
  File "./usage.py", line 6, in <module>
    comp_mob["UsageCode"].value = "Usage_TopLevel"
  File "aaf/property.pyx", line 63, in aaf.property.PropertyItem.value.__set__
  File "aaf/property.pyx", line 187, in aaf.property.PropertyValue.set_value
  File "aaf/define/TypeDefExtEnum.pyx", line 110, in aaf.define.TypeDefExtEnum.set_value
  File "aaf/util.pyx", line 23, in aaf.util.error_check
RuntimeError: failed with [-2146303638]: illegal value - illegal value
```

Python 2.7.13 and 3.6.2 on macOS 10.12.6
pyaaf branch: dev

**Comment by markreidvfx** [comment]
"UsageCode" is a ExtEnum type, setting them is currently hit or miss, 
try the convenience property instead.

```python
import aaf

f = aaf.open()
comp_mob = f.create.CompositionMob()
comp_mob.usage_code = "Usage_TopLevel"
```

**Comment by cbenhagen** [comment]
Thank you!
